version: '3'
services:
  app:
    container_name: uptime_monitoring_api
    restart: always
    build: .
    ports:
      - '3000:3000'
    networks:
      - uptime-app
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - uptime-app      
    volumes:
      - mongo-data:/data/db
networks:
  uptime-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local